   name: Deploy Slidev to GitHub Pages

   permissions:
      contents: write  # Allows writing to repository contents (e.g., gh-pages branch)
      pages: write    # Allows managing GitHub Pages
      id-token: write # Optional, for additional authentication

   on:
     push:
       branches: [main]

   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest
       steps:
         # 检出代码
         - name: Checkout
           uses: actions/checkout@v3

         # 设置 Node.js 环境
         - name: Setup Node
           uses: actions/setup-node@v3
           with:
             node-version: '18'
             cache: 'npm'

         # 安装依赖
         - name: Install Dependencies
           run: npm ci

         # 构建第一套幻灯片
         - name: Build Presentation 1
           run: |
            mkdir -p dist
            npx slidev build --entry slide1.md --out dist/p1 --base /osslidev/p1/
            ls dist

         # 构建第二套幻灯片
         - name: Build Presentation 2
           run: |
             npx slidev build --entry slide2.md --out dist/p2 --base /osslidev/p2/
             ls dist

         # 创建首页
         - name: Create Index Page
           run: |
             mkdir -p dist
             echo "<html><body><h1>My Presentations</h1><ul><li><a href='/p1/'>Presentation 1</a></li><li><a href='/p2/'>Presentation 2</a></li></ul></body></html>" > dist/index.html
             ls dist

         # 部署到 GitHub Pages
         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./dist

